In [1]:
# NumPy -->  n o'lchovli arry larni saqlaydi

!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [4]:
arr=np.array([2,3,4,5])
print(arr)

[2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(4,)


In [7]:
print(arr.dtype)

int64


In [8]:
np.random.randint(1,10,3)

array([7, 4, 1], dtype=int32)

In [11]:
# ikki o'lchovli random son hozil qilish

arr=np.array([
    [2,3,4],
    [4,7,3]])
print(arr)
print(arr.shape)

[[2 3 4]
 [4 7 3]]
(2, 3)


In [16]:
arr=np.array([2,3,5,6,7], ndmin=4)
print(arr.shape)
print(arr)

(1, 1, 1, 5)
[[[[2 3 5 6 7]]]]


In [17]:
arr = np.random.randint(10, size=5)
print(arr)

[3 5 7 2 6]


In [18]:
arr[1]=3
print(arr)

[3 3 7 2 6]


In [19]:
r = np.random.randint(100, size=(3,4))
r

array([[17, 29, 64, 81],
       [53, 41, 23, 14],
       [73, 89, 25, 44]], dtype=int32)

In [22]:
r[2,1]

np.int32(89)

In [23]:
r = np.random.randint(10, size=5)
r

array([0, 7, 1, 6, 4], dtype=int32)

In [25]:
r[1:3]

array([7, 1], dtype=int32)

In [27]:
r[::-1]

array([4, 6, 1, 7, 0], dtype=int32)

In [7]:
r = np.random.randint(100, size=(5, 4))
print(r)

[[78  8 83 48]
 [71 68 49 28]
 [67 84 95 33]
 [70 73 19 99]
 [ 5 18 82 35]]


In [11]:
r[3]

array([70, 73, 19, 99], dtype=int32)

In [12]:
r[3][2]

np.int32(19)