In [3]:
import numpy as np

In [2]:
a=np.random.randint(20, size=10)
b=np.random.randint(20, size=10)
print(a)
print()
print(b)

[16  0 10  8  3 14  5  9  5 17]

[13  6 16 10  9 16  9  5  8 12]


In [3]:
c=a+b
c

array([29,  6, 26, 18, 12, 30, 14, 14, 13, 29], dtype=int32)

In [4]:
c=a-b
c

array([ 3, -6, -6, -2, -6, -2, -4,  4, -3,  5], dtype=int32)

In [5]:
c=a/b
c

array([1.23076923, 0.        , 0.625     , 0.8       , 0.33333333,
       0.875     , 0.55555556, 1.8       , 0.625     , 1.41666667])

In [6]:
c=a*b
c

array([208,   0, 160,  80,  27, 224,  45,  45,  40, 204], dtype=int32)

In [9]:
#  a va b ning skalyar ko'paytmasini topib beradi

c=sum(a*b)

print(a)
print()
print(b)
print()
print(c)

[ 1 18  2 16  9  9  4 17 19 14]

[13  6 16 10  9 16  9  5  8 12]

979


In [11]:
# "dot" ham a va b ning skalyar ko'paytmasini topib beradi

c=np.dot(a, b)
c

np.int32(979)

In [12]:
# "inner" ham a va b ning skalyar ko'paytmasini topib beradi

c=np.inner(a, b)
c

np.int32(979)

In [14]:
# outer --> tashqi ko'paytma

c=np.outer(a, b)
print(a)
print()
print(b)
print()
print(c)

[ 1 18  2 16  9  9  4 17 19 14]

[13  6 16 10  9 16  9  5  8 12]

[[ 13   6  16  10   9  16   9   5   8  12]
 [234 108 288 180 162 288 162  90 144 216]
 [ 26  12  32  20  18  32  18  10  16  24]
 [208  96 256 160 144 256 144  80 128 192]
 [117  54 144  90  81 144  81  45  72 108]
 [117  54 144  90  81 144  81  45  72 108]
 [ 52  24  64  40  36  64  36  20  32  48]
 [221 102 272 170 153 272 153  85 136 204]
 [247 114 304 190 171 304 171  95 152 228]
 [182  84 224 140 126 224 126  70 112 168]]


In [17]:
# "all " bu noldan fraqlilikka yoki hammasi True likka tkshiradi

print(a)
c=np.all(a)
print(c)

[ 1 18  2 16  9  9  4 17 19 14]
True


In [7]:
# exponentasini topish

a=np.random.randint(20, size=10)
print(a)
c=np.exp(a)
c

[11 13  5 10  3  0  5 19 17  6]


array([5.98741417e+04, 4.42413392e+05, 1.48413159e+02, 2.20264658e+04,
       2.00855369e+01, 1.00000000e+00, 1.48413159e+02, 1.78482301e+08,
       2.41549528e+07, 4.03428793e+02])

In [18]:
a=np.random.randint(20, size=10)
print(a)
c=np.sum(a)
c

[ 8  9  9  3 11  7 19 11 15 19]


np.int64(111)

In [4]:
a=np.random.randint(2, size=(10, ), dtype=bool)
b=np.random.randint(2, size=(10, ), dtype=bool)
print(a)
print()
print(b)

[ True  True False False False False  True False False False]

[False False False  True False  True False  True False  True]


In [5]:
c=np.logical_and(a,b)
c

array([False, False, False, False, False, False, False, False, False,
       False])

In [6]:
c=np.logical_or(a,b)
c

array([ True,  True, False,  True, False,  True,  True,  True, False,
        True])

In [7]:
c=np.logical_not(a)
c

array([False, False,  True,  True,  True,  True, False,  True,  True,
        True])

In [10]:
c=a
c is a

True

In [11]:
a=np.random.randint(20, size=10)
b=np.random.randint(20, size=10)
print(a)
print()
print(b)

[13  9  9 19 13 12 10 17 18 18]

[ 3 18 11 16  2  2  4 15 13 12]


In [12]:
17 in a

True

In [15]:
# allclose --> ikkita vektor bersak ularning hamma qiymatlari tengmi hammasini solishtirib beradi

print(a)
c = np.allclose(a)
c

[13  9  9 19 13 12 10 17 18 18]


TypeError: allclose() missing 1 required positional argument: 'b'

MATRITSALAR USTIDA AMALLAR

In [16]:
A = np.random.randint(20, size=(4,3))
B = np.random.randint(20, size=(4,3))
print(A)
print()
print(B)

[[18 15 12]
 [16  0  5]
 [ 6 11  7]
 [ 8  3 12]]

[[ 8 14 15]
 [ 7 14  9]
 [ 5 14  8]
 [15  5  9]]


In [17]:
c=A*B
c

array([[144, 210, 180],
       [112,   0,  45],
       [ 30, 154,  56],
       [120,  15, 108]], dtype=int32)

In [18]:
A = np.random.randint(20, size=(5,3))
B = np.random.randint(20, size=(3,4))
print(A)
print()
print(B)

[[10 10 10]
 [ 9 12 16]
 [14  6 11]
 [ 6  6 12]
 [11 19  7]]

[[17 15  6 10]
 [ 8 17 15  1]
 [ 7  7 14  3]]


In [20]:
# Matritsani matritsaga ko'paytirish

c=np.matmul(A, B)
print(c)

[[320 390 350 140]
 [361 451 458 150]
 [363 389 328 179]
 [234 276 294 102]
 [388 537 449 150]]


In [21]:
A = np.random.randint(20, size=(5,3))
B = np.random.randint(20, size=(3,4))
print(A)
print()
print(B)

[[ 0  7  3]
 [11 13  4]
 [ 5  7  1]
 [ 7 11 19]
 [ 3 11  3]]

[[ 9 15  2  9]
 [ 5  4  0 14]
 [ 5 10  6 17]]


In [22]:
# A matritsaning yi'g'indisi

np.sum(A)

np.int64(105)

In [23]:
# A matritsaning har bir qatorining yi'g'indisi

np.sum(A, axis=1)

array([10, 28, 13, 37, 17])

In [24]:
# A matritsaning har bir ustunining yi'g'indisi

np.sum(A, axis=0)

array([26, 49, 30])

In [25]:
np.max(A)

np.int32(19)

In [26]:
# Har bir qator bo'yicha maksimallar

np.max(A, axis=1)

array([ 7, 13,  7, 19, 11], dtype=int32)

In [27]:
# Har bir qator bo'yicha minimumllar

np.max(A, axis=0)

array([11, 13, 19], dtype=int32)

In [28]:
# Matritsaning o'rta arfmetigini topish. Hamma elementlarini qo'shib qo'shiluvchilaring soniga bo'ladi

np.mean(A)

np.float64(7.0)