In [2]:
import numpy as np

In [9]:
a=np.zeros(shape=(2,4))
b= np.zeros_like(a)
print(b)

c=np.ones(shape=(3,4))
c

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [12]:
# linspace --> 0 dan 1 gacha 10 ta bo'lakka bo'lib beradi

a=np.linspace(0, 1, 10)
a

a=np.linspace(0, 1, 10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
a=np.zeros(shape=(3,3))
np.fill_diagonal(a, val=1)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a = np.random.rand(3,4)
a

array([[0.70994947, 0.89133961, 0.80269046, 0.83767886],
       [0.17051564, 0.76042092, 0.15416061, 0.97456881],
       [0.3007321 , 0.21183703, 0.40585666, 0.35319285]])

In [22]:
a[0] = np.zeros(4)
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.70021918, 0.00416924, 0.76918257, 0.34906665],
       [0.57160467, 0.32546805, 0.14920105, 0.5582596 ]])

In [9]:
a[:, 1] = np.zeros(3)
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.17051564, 0.        , 0.15416061, 0.97456881],
       [0.        , 0.        , 0.        , 0.        ]])

In [8]:


a[::2] = np.zeros(shape=(2,4))
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.17051564, 0.76042092, 0.15416061, 0.97456881],
       [0.        , 0.        , 0.        , 0.        ]])

Turlar bilan ishlash

In [16]:
a.dtype
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.17051564, 0.        , 0.15416061, 0.97456881],
       [0.        , 0.        , 0.        , 0.        ]])

In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
#  a ni typeni o'zgartirish


b=a.astype(np.float32)
b

array([[0.        , 0.        , 0.        , 0.        ],
       [0.17051564, 0.        , 0.15416062, 0.9745688 ],
       [0.        , 0.        , 0.        , 0.        ]], dtype=float32)

In [17]:
# a va b ni qanchalik yaqinligini tekshirish "allclose"

np.allclose(a,b)

True

In [18]:
b=np.random.rand(3,4)
b

array([[0.28286409, 0.09340667, 0.10335641, 0.58658678],
       [0.39437319, 0.44172652, 0.64209604, 0.17562677],
       [0.82070226, 0.89369051, 0.81651331, 0.40676721]])

In [ ]:
# matritsaning o'lchamini o'zgartirish


In [19]:
a=b.copy()
a

array([[0.28286409, 0.09340667, 0.10335641, 0.58658678],
       [0.39437319, 0.44172652, 0.64209604, 0.17562677],
       [0.82070226, 0.89369051, 0.81651331, 0.40676721]])

In [21]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# list qatorni matritsaga o'tkazish

a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a=np.arange(12)
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a=np.arange(12)
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a=np.arange(12)
b=a.reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])