In [1]:
import numpy as np

In [2]:
a=np.random.randint(20, size=10)
b=np.random.randint(20, size=10)
print(a)
print()
print(b)

[16  0 10  8  3 14  5  9  5 17]

[13  6 16 10  9 16  9  5  8 12]


In [3]:
c=a+b
c

array([29,  6, 26, 18, 12, 30, 14, 14, 13, 29], dtype=int32)

In [4]:
c=a-b
c

array([ 3, -6, -6, -2, -6, -2, -4,  4, -3,  5], dtype=int32)

In [5]:
c=a/b
c

array([1.23076923, 0.        , 0.625     , 0.8       , 0.33333333,
       0.875     , 0.55555556, 1.8       , 0.625     , 1.41666667])

In [6]:
c=a*b
c

array([208,   0, 160,  80,  27, 224,  45,  45,  40, 204], dtype=int32)

In [9]:
#  a va b ning skalyar ko'paytmasini topib beradi

c=sum(a*b)

print(a)
print()
print(b)
print()
print(c)

[ 1 18  2 16  9  9  4 17 19 14]

[13  6 16 10  9 16  9  5  8 12]

979


In [11]:
# "dot" ham a va b ning skalyar ko'paytmasini topib beradi

c=np.dot(a, b)
c

np.int32(979)

In [12]:
# "inner" ham a va b ning skalyar ko'paytmasini topib beradi

c=np.inner(a, b)
c

np.int32(979)

In [14]:
# outer --> tashqi ko'paytma

c=np.outer(a, b)
print(a)
print()
print(b)
print()
print(c)

[ 1 18  2 16  9  9  4 17 19 14]

[13  6 16 10  9 16  9  5  8 12]

[[ 13   6  16  10   9  16   9   5   8  12]
 [234 108 288 180 162 288 162  90 144 216]
 [ 26  12  32  20  18  32  18  10  16  24]
 [208  96 256 160 144 256 144  80 128 192]
 [117  54 144  90  81 144  81  45  72 108]
 [117  54 144  90  81 144  81  45  72 108]
 [ 52  24  64  40  36  64  36  20  32  48]
 [221 102 272 170 153 272 153  85 136 204]
 [247 114 304 190 171 304 171  95 152 228]
 [182  84 224 140 126 224 126  70 112 168]]


In [17]:
# "all " bu noldan fraqlilikka yoki hammasi True likka tkshiradi

print(a)
c=np.all(a)
print(c)

[ 1 18  2 16  9  9  4 17 19 14]
True


In [7]:
# exponentasini topish

a=np.random.randint(20, size=10)
print(a)
c=np.exp(a)
c

[11 13  5 10  3  0  5 19 17  6]


array([5.98741417e+04, 4.42413392e+05, 1.48413159e+02, 2.20264658e+04,
       2.00855369e+01, 1.00000000e+00, 1.48413159e+02, 1.78482301e+08,
       2.41549528e+07, 4.03428793e+02])

In [18]:
a=np.random.randint(20, size=10)
print(a)
c=np.sum(a)
c

[ 8  9  9  3 11  7 19 11 15 19]


np.int64(111)

In [4]:
a=np.random.randint(2, size=(10, ), dtype=bool)
b=np.random.randint(2, size=(10, ), dtype=bool)
print(a)
print()
print(b)

[ True  True False False False False  True False False False]

[False False False  True False  True False  True False  True]


In [5]:
c=np.logical_and(a,b)
c

array([False, False, False, False, False, False, False, False, False,
       False])

In [6]:
c=np.logical_or(a,b)
c

array([ True,  True, False,  True, False,  True,  True,  True, False,
        True])

In [7]:
c=np.logical_not(a)
c

array([False, False,  True,  True,  True,  True, False,  True,  True,
        True])

In [10]:
c=a
c is a

True

In [11]:
a=np.random.randint(20, size=10)
b=np.random.randint(20, size=10)
print(a)
print()
print(b)

[13  9  9 19 13 12 10 17 18 18]

[ 3 18 11 16  2  2  4 15 13 12]


In [12]:
17 in a

True

In [15]:
# allclose --> ikkita vektor bersak ularning hamma qiymatlari tengmi hammasini solishtirib beradi

print(a)
c = np.allclose(a)
c

[13  9  9 19 13 12 10 17 18 18]


TypeError: allclose() missing 1 required positional argument: 'b'

MATRITSALAR USTIDA AMALLAR

In [16]:
A = np.random.randint(20, size=(4,3))
B = np.random.randint(20, size=(4,3))
print(A)
print()
print(B)

[[18 15 12]
 [16  0  5]
 [ 6 11  7]
 [ 8  3 12]]

[[ 8 14 15]
 [ 7 14  9]
 [ 5 14  8]
 [15  5  9]]


In [17]:
c=A*B
c

array([[144, 210, 180],
       [112,   0,  45],
       [ 30, 154,  56],
       [120,  15, 108]], dtype=int32)

In [18]:
A = np.random.randint(20, size=(5,3))
B = np.random.randint(20, size=(3,4))
print(A)
print()
print(B)

[[10 10 10]
 [ 9 12 16]
 [14  6 11]
 [ 6  6 12]
 [11 19  7]]

[[17 15  6 10]
 [ 8 17 15  1]
 [ 7  7 14  3]]


In [20]:
# Matritsani matritsaga ko'paytirish

c=np.matmul(A, B)
print(c)

[[320 390 350 140]
 [361 451 458 150]
 [363 389 328 179]
 [234 276 294 102]
 [388 537 449 150]]


In [21]:
A = np.random.randint(20, size=(5,3))
B = np.random.randint(20, size=(3,4))
print(A)
print()
print(B)

[[ 0  7  3]
 [11 13  4]
 [ 5  7  1]
 [ 7 11 19]
 [ 3 11  3]]

[[ 9 15  2  9]
 [ 5  4  0 14]
 [ 5 10  6 17]]


In [22]:
# A matritsaning yi'g'indisi

np.sum(A)

np.int64(105)

In [23]:
# A matritsaning har bir qatorining yi'g'indisi

np.sum(A, axis=1)

array([10, 28, 13, 37, 17])

In [24]:
# A matritsaning har bir ustunining yi'g'indisi

np.sum(A, axis=0)

array([26, 49, 30])

In [25]:
np.max(A)

np.int32(19)

In [26]:
# Har bir qator bo'yicha maksimallar

np.max(A, axis=1)

array([ 7, 13,  7, 19, 11], dtype=int32)

In [27]:
# Har bir qator bo'yicha minimumllar

np.max(A, axis=0)

array([11, 13, 19], dtype=int32)

In [28]:
# Matritsaning o'rta arfmetigini topish. Hamma elementlarini qo'shib qo'shiluvchilaring soniga bo'ladi

np.mean(A)

np.float64(7.0)

In [3]:
A = np.random.randint(20, size=(5,3,4))
A

array([[[ 4,  5,  3,  0],
        [17, 13,  7,  6],
        [ 8,  0,  3,  9]],

       [[ 7, 10,  5,  7],
        [17,  2, 18, 10],
        [17, 12, 10, 10]],

       [[ 7, 12,  9,  0],
        [13, 19, 13, 11],
        [ 4, 19, 18,  3]],

       [[15, 16,  6,  0],
        [15,  4, 11,  5],
        [ 7, 15,  5,  5]],

       [[ 2,  4,  2, 11],
        [ 7, 11, 16,  2],
        [ 3, 17,  1,  7]]], dtype=int32)

In [5]:
np.sum(A, axis=1)

array([[29, 18, 13, 15],
       [41, 24, 33, 27],
       [24, 50, 40, 14],
       [37, 35, 22, 10],
       [12, 32, 19, 20]])

In [6]:
np.sum(A)

np.int64(515)

In [7]:
np.sum(A, axis=2)

array([[12, 43, 20],
       [29, 47, 49],
       [28, 56, 44],
       [37, 35, 32],
       [19, 36, 28]])

In [8]:
np.sum(A, axis=(0,1,2))

np.int64(515)

In [9]:
np.sum(A, axis=(0,1))

array([143, 159, 127,  86])

In [17]:
A = np.random.randint(20, size=(5,3))
A

array([[ 5, 12,  7],
       [ 7, 18, 13],
       [ 4, 11, 13],
       [ 9,  1,  6],
       [ 9,  3,  6]], dtype=int32)

In [13]:
# matritsani tronspose qilish (90 gradusga burish)

A.T

array([[ 2, 19, 15,  1,  6],
       [ 4, 17, 17,  1,  7],
       [17, 10, 17, 12, 19]], dtype=int32)

In [14]:
# matritsani oddiy vektor  ko'rinishiga o'tkazib beradi

c=A.ravel()
print(c)

[ 2  4 17 19 17 10 15 17 17  1  1 12  6  7 19]


In [20]:
np.save('A.npy', A)
np.savetxt('A.txt', A, fmt="%d")

In [19]:
# xotiraga yuklab beradi

A=np.load('A.npy')

In [21]:
np.savetxt('AB.txt', A, fmt="%d", delimiter=',')

1. VEKTOR va MATRITSA O'RTASIDAGI amallar
2. SOFTMAX operation

In [22]:
import numpy as np

In [27]:
A=np.load('A.npy')
A


array([[ 5, 12,  7],
       [ 7, 18, 13],
       [ 4, 11, 13],
       [ 9,  1,  6],
       [ 9,  3,  6]], dtype=int32)

In [31]:
# tepadagi matritsaga ustunlar bo'yicha shu vektorni qo'shish

a=np.array([0,1,2])


In [32]:
B=A+a
B

array([[ 5, 13,  9],
       [ 7, 19, 15],
       [ 4, 12, 15],
       [ 9,  2,  8],
       [ 9,  4,  8]])

In [34]:
b=np.array([0,1,2,3,4]).reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
C=A+b
C

array([[ 5, 12,  7],
       [ 8, 19, 14],
       [ 6, 13, 15],
       [12,  4,  9],
       [13,  7, 10]])

SOFTMAX

In [45]:
X=np.random.rand(100,5)
exp_X = np.exp(X)
# print(exp_X)
# keepdims=True ---> o'lchamlarni saqlab qolish: reshape(1,100) ni o'rniga keepdims=True yoziladi 
row_sum = np.sum(exp_X, axis=1, keepdims=True)
probs = exp_X/row_sum
print(probs)

[[0.22850876 0.16076728 0.18163906 0.2514944  0.17759049]
 [0.14510721 0.19856791 0.15830245 0.35970194 0.13832048]
 [0.1603385  0.18192827 0.17673094 0.22924724 0.25175505]
 [0.21292004 0.14005884 0.26919367 0.23182179 0.14600567]
 [0.15602401 0.17435787 0.21020689 0.21286901 0.24654221]
 [0.21529426 0.1480915  0.15389228 0.32507366 0.15764831]
 [0.16532712 0.22241691 0.12357029 0.19936285 0.28932283]
 [0.13747693 0.21578247 0.20303999 0.17480704 0.26889357]
 [0.16911162 0.25726847 0.1564982  0.2128431  0.2042786 ]
 [0.25825754 0.25651701 0.12805974 0.19114777 0.16601795]
 [0.24160317 0.2828978  0.17470349 0.13408008 0.16671546]
 [0.31627996 0.12312619 0.15828216 0.18500448 0.21730721]
 [0.34170682 0.15019685 0.14411541 0.14324348 0.22073744]
 [0.17094375 0.19776739 0.17725354 0.20568852 0.24834681]
 [0.22191423 0.14265596 0.16315207 0.20431092 0.26796681]
 [0.14981439 0.23414453 0.23642526 0.22469652 0.15491929]
 [0.11409158 0.2564218  0.14284681 0.22377962 0.2628602 ]
 [0.18348397 0

In [46]:
probs[0]

array([0.22850876, 0.16076728, 0.18163906, 0.2514944 , 0.17759049])

In [2]:
a=np.random.randint(20, size=10)
a

array([16,  6,  7,  7, 13, 11, 12,  7, 16,  1], dtype=int32)

In [3]:
a.shape[0]

10